parameters:
    synolia.oroneo.form.type.import.class:                  Synolia\Bundle\OroneoBundle\Form\Type\ImportType
    synolia.oroneo.form.type.mapping.config.class:          Synolia\Bundle\OroneoBundle\Form\Type\MappingConfigType
    synolia.oroneo.form.config.mapping.category.class:      Synolia\Bundle\OroneoBundle\Form\Type\CategoryMappingConfigType
    synolia.oroneo.form.config.mapping.product.class:       Synolia\Bundle\OroneoBundle\Form\Type\ProductMappingConfigType
    synolia.oroneo.form.type.mapping.class:                 Synolia\Bundle\OroneoBundle\Form\Type\MappingType
    synolia.oroneo.form.type.mapping.category.class:        Synolia\Bundle\OroneoBundle\Form\Type\CategoryMappingType
    synolia.oroneo.form.type.mapping.product.class:         Synolia\Bundle\OroneoBundle\Form\Type\ProductMappingType
    synolia.oroneo.form.type.localization.config.class:     Synolia\Bundle\OroneoBundle\Form\Type\LocalizationMappingConfigType
    synolia.oroneo.form.type.localization.class:            Synolia\Bundle\OroneoBundle\Form\Type\LocalizationMappingType
    synolia.oroneo.form.type.mapping.master_category.class: Synolia\Bundle\OroneoBundle\Form\Type\MasterCategoryType

services:
    synolia.oroneo.form.type.import:
        class: '%synolia.oroneo.form.type.import.class%'
        arguments: ['@oro_importexport.processor.registry']
        tags:
            - { name: form.type, alias: synolia_oroneo_import_form }

    # Mapping
    synolia.oroneo.form.type.mapping.collection:
        class: '%synolia.oroneo.form.type.mapping.config.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_mapping_config }

    synolia.oroneo.form.type.mapping:
        class: '%synolia.oroneo.form.type.mapping.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_mapping }

    synolia.oroneo.form.type.config.mapping.category:
        class: '%synolia.oroneo.form.config.mapping.category.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_category_mapping }

    synolia.oroneo.form.type.config.mapping.product:
        class: '%synolia.oroneo.form.config.mapping.product.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_product_mapping }

    synolia.oroneo.form.type.config.mapping.localization:
        class: '%synolia.oroneo.form.type.localization.config.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_localization_mapping }

    # Types
    synolia.oroneo.form.type.mapping.category:
        class: '%synolia.oroneo.form.type.mapping.category.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_category_mapping_type }

    synolia.oroneo.form.type.mapping.product:
        class: '%synolia.oroneo.form.type.mapping.product.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_product_mapping_type }

    synolia.oroneo.form.type.mapping.localization:
        class: '%synolia.oroneo.form.type.localization.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_localization_mapping_type }

    synolia.oroneo.form.type.mapping.master_category:
        class: '%synolia.oroneo.form.type.mapping.master_category.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_master_category_type }
