oro_menu_config:
    items:
        synolia_akeneo_tab:
            label:           'Akeneo'
            uri:             '#'
            extras:
                icon:        icon-briefcase
                position:    9999999999

        synolia_akeneo_import:
            label:           'synolia.oroneo.import_page.label'
            route:           'synolia_Oroneo_import'
            extras:
                position:    200
                routes:      ['/^oroneo/']
                description: 'synolia.oroneo.import_page.description'

        synolia_akeneo_configuration:
            label:           'synolia.oroneo.configuration_page.label'
            route:           'synolia_Oroneo_configuration'
            extras:
                position:    300
                description: 'synolia.oroneo.configuration_page.description'

    tree:
        application_menu:
            children:
                synolia_akeneo_tab:
                    children:
                        synolia_akeneo_import: ~
                        synolia_akeneo_configuration: ~
