parameters:
    synolia.import.subscriber.category.class:        Synolia\Bundle\OroneoBundle\EventSubscriber\CategorySubscriber
    synolia.import.subscriber.attribute.class:       Synolia\Bundle\OroneoBundle\EventSubscriber\AttributeSubscriber
    synolia.import.subscriber.product.class:         Synolia\Bundle\OroneoBundle\EventSubscriber\ProductSubscriber
    synolia.oroneo.import.service.class:   Synolia\Bundle\OroneoBundle\Service\ImportService
    synolia.oroneo.oro_field_select.class: Synolia\Bundle\OroneoBundle\Service\OroFieldSelectService

services:
    synolia_oroneo.category.repository:
        class: Synolia\Bundle\OroneoBundle\Repository\CategoryRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    synolia.import.subscriber.category:
        class: '%synolia.import.subscriber.category.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_dataaudit.listener.entity_listener'
        tags:
            - { name: kernel.event_subscriber }

    synolia.import.subscriber.attribute:
        class: '%synolia.import.subscriber.attribute.class%'
        arguments:
            - '@oro_entity_extend.extend.entity_processor'
            - '@oro_entity_config.config_manager'
        tags:
            - { name: kernel.event_subscriber }

    synolia.import.subscriber.product:
        class: '%synolia.import.subscriber.product.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_dataaudit.listener.entity_listener'
        tags:
            - { name: kernel.event_subscriber }

    synolia.oroneo.import.service:
        class: '%synolia.oroneo.import.service.class%'
        arguments:
            - '@translator'

    synolia.oroneo.oro_field_select:
        class: '%synolia.oroneo.oro_field_select.class%'
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_locale.helper.localization'
