parameters:
    synolia.import.subscriber.category.class: Synolia\Bundle\OroneoBundle\EventSubscriber\CategorySubscriber
    synolia.import.subscriber.product.class:  Synolia\Bundle\OroneoBundle\EventSubscriber\ProductSubscriber
    synolia.oroneo.import.manager.class:      Synolia\Bundle\OroneoBundle\Manager\ImportManager
    synolia.oroneo.oro_field_select.class:    Synolia\Bundle\OroneoBundle\Manager\OroFieldSelectManager

services:
    synolia_oroneo.category.repository:
        class: Synolia\Bundle\OroneoBundle\Repository\CategoryRepository
        arguments:
            - '@oro_entity.doctrine_helper'

    synolia.oroneo.import.manager:
        class: '%synolia.oroneo.import.manager.class%'
        arguments:
            - '@translator'
            - '@oro_importexport.handler.import.http'
            - '@oro_importexport.processor.registry'
            - '@oro_config.global'
            - '@oro_entity_extend.extend.entity_processor'

    synolia.oroneo.oro_field_select:
        class: '%synolia.oroneo.oro_field_select.class%'
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_locale.helper.localization'
            - '@oro_catalog.repository.category'
